apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: onyxia
    repo: https://inseefrlab.github.io/onyxia
    version: 10.32.0
    releaseName: onyxia
    namespace: onyxia
    valuesFile: values.yaml

patches:
  - path: patch-dns.yaml
    target:
      kind: Deployment
      name: onyxia-api
